# Configurations for the EventHorizon plugin

# default integer value for tournament timer (in seconds)
tournament-timer: 3600

# default weights for event frequency
# values relative to each other and do not need to add up to any specific number
event:
  frequency: 10
  posWeight: 3
  negWeight: 3
  neutralWeight: 3

# to disable events, comment out the event name by putting "#" in front of it
enabled-events:
- "Fasting" #attribute: negative
- "GrowthSpurt" #attribute: neutral
- "HoneyIShrunkTheKids" #attribute: negative
- "LifestealOnly" #attribute: negative
- "ZeroGravity" #attribute: neutral
- "IceIsNice" #blockModification: neutral
- "BlockDropShuffle" #dropModification: neutral
- "DoubleOrNothing" #dropModification: negative
- "MobDropShuffle" #dropModification: neutral
- "FoodComa" #effects: neutral
- "GottaGoFast" #effects: positive
- "Overmine" #effects: positive
- "SecondWind" #effects: positive
- "YoureTooSlow" #effects: negative
- "FlightSchool" #inventoryAdjustment: positive
- "SpoiledFood" #inventoryAdjustment: negative
- "Feast" #itemSpawn: positive
- "OreDropParty" #itemSpawn: positive
- "ChickenFlock" #mobSpawn: positive
- "CowHerd" #mobSpawn: positive
- "DropCreeper" #mobSpawn: negative
- "RandomMobSpawn" #mobSpawn: neutral
- "WolfPack" #mobSpawn: negative
- "ZombieHorde" #mobSpawn: negative
- "ZombieInvasion" #mobSpawn: negative


